### ISSUE TITLE
which encoding?

### ISSUE THREAD

**Issue by john916zhang** [morphgnt/strongs-dictionary-xml#2]
Hi there,

Thanks for providing this wonderful dictionary. But I have problems to use it. The Greek words in this dictionary seem using different an encoding. It cannot match with other libraries like https://github.com/morphgnt/sblgnt.

Any information will be appreciated.

**Comment by emg** [comment]
Hello,

thank you for your kind words.

Each lemma in the dictionary exists in both BETA encoding (ASCII transliteration) and in Unicode.  The Unicode version is what you need if you want to match it with MorphGNT SBLGNT.  You might find that some words don't match due to differences in NFKC / NFD Unicode normalization.

However, what you are experiencing is probably that some of the lemmas in the MorphGNT SBLGNT are not the same as what is found in Strong's dictionary, even though the underlying word is the same.  

Matching up the lemmas from MorphGNT SBLGNT with Strong's dictionary is a large undertaking.  James Tauber @jtauber and I are currently working on a resolution to this issue, but I am not sure how far we are in that work.

Sorry to not be able to be of more help.

Instead of using Strong's dictionary, you might want to check out Abbott-Smith's dictionary, which is also available digitally here on GitHub:

https://github.com/translatable-exegetical-tools/Abbott-Smith

Strong's dictionary, while widely used, is not good quality in its definitions and overall scholarship.  Abbott-Smith, on the other hand, is excellent on both accounts.  It might also be easier to match up the lemmas of Abbott-Smith with MorphGNT SBLGNT.


Best wishes,

Ulrik Sandborg-Petersen

**Comment by john916zhang** [comment]
Thank you very much, Ulrik. The Abbott-Smith dictionary seems old. I am interested in the dictionary by Bill Mounce: https://www.billmounce.com/greek-dictionary. Gladly they make it public: https://github.com/billmounce/dictionary

**Comment by john916zhang** [comment]
I know the problem now. The Unicode for Greek alphabets has two parts: Greek and Coptic, Greek Extended. 

https://en.wikipedia.org/wiki/Greek_Extended
https://en.wikipedia.org/wiki/Greek_and_Coptic

In these two tables, there are some characters having the same look but different code. It makes confusions. To solve it, we can use "String.normalize()" in Javascript.

For Python, please refer to the following article:
https://jktauber.com/articles/python-unicode-ancient-greek/

**Comment by emg** [comment]
Thanks.  It would be very helpful if you could let me know whether you found any characters from the monotonic part of the Greek Unicode sections.  All codes should be from the polytonic part (Greek Extended).  

If you could even let me know _which_ codes you have found from the monotonic part, I can more easily track it down and fix it.  

Thanks so much in advance.

**Comment by emg** [comment]
So sorry, I spoke too soon.

The Greek Extended code point range is not enough to encode Koine Greek.  We need the Greek Unicode range for all letters which do not carry accents, breathing marks, iota subscribts, iota adscripts, and diarhesis.

So I am not sure it would be helpful for me if you pointed out the characters that are not in the Greek Extended range, but which are used in the dictionary.

Sorry for the confusion.

Ulrik
